### ISSUE TITLE
[BUG] Android low end devices with virtual sensors are very sensitive to tilts

### ISSUE THREAD

**Issue by gladiuscode** [gladiuscode/react-native-orientation-director#77]
**Describe the bug**
Currently, it seems that low end devices running Android with virtual sensors, experience too many orientation changes due to tilt triggering the `SensorManager` implementation.

**To Reproduce**
I have yet to reproduce it since I don't own a low end Android device with such characteristics, but a user reported this issue here #74.

**Expected behavior**
It shouldn't trigger too many orientation device changes alongside interface one on low end devices.

**Smartphone (please complete the following information):**
 - OS: Android
 - Device: Any Low End Device
 - Version N/A

**Comment by gladiuscode** [comment]
I've read the [documentation](https://developer.android.com/develop/sensors-and-location/sensors/sensors_position?hl=it#sensors-pos-orient) again and I can say that I had forgotten to pass a proper value during the sensor init, so It may be that the reason why we experience such issue in low end devices.

I don't like to consider it fixed by simply passing a forgotten value, we need to properly test this out, I just need to understand how, because the emulator is not really reliable

**Comment by p1d3c** [comment]
some updates?

**Comment by p1d3c** [comment]
Tested ur changes on Xiaomi Redmi Note 10S, 13 android version.
Still have issue with sensor sensitivity. Especially when holding phone in portrait orientation (like default holding phone in hand) and trying to tilit him about 30-45 degrees left or right side

**Comment by gladiuscode** [comment]
Hi @p1d3c,
I can't get hold of a low end android device, so I can't test everything out.

Although your feedback are actually helpful, it means that the patch following the documentation doesn't fix it unfortunately.

I'll try to think about a way to fix this properly and update this issue to ask for tests if you can!

**Comment by p1d3c** [comment]
Hi @gladiuscode, I will test ASAP. Thank you!
